### ISSUE TITLE
Make button for homepage

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/fractal#1]
So far:

```css
button {
background-color: #2a7ae2; // $brand-color
color: white;
font-size: 2em;
}
```

```html
<a href="#">
<button>
Repo
</button>
</a>
```
